parameters:
  - name: runon
    displayName: runon
    type: string
    default: ubuntu-latest
    values:
      - ubuntu-latest
      - windows-latest
  - name: mainjs
    displayName: mainjs
    type: string
    default: main.js

jobs:
  - job: osvrrepoaes
    displayName: osvrrepoaes
    pool:
      vmImage: ${{ parameters.runon }}
    steps:
      - task: UseNode@1
        displayName: Install NodeJS 18.x
        inputs:
          version: "18.x"

      - task: Bash@3
        displayName: Clone and decrypt dist
        env:
          SYTEM_ACCESS_TOKEN: $(System.AccessToken)
        inputs:
          targetType: inline
          script: |
            file=./dist/oAESFile.js

            git clone https://o-adv@dev.azure.com/o-adv/o-svr-repo-aes/_git/o-svr-repo-aes2 ./dist

            if [ ! -f "$file" ]; then
              git clone https://o-adv@dev.azure.com/o-adv/o-svr-repo-aes/_git/o-svr-repo-aes ./dist
            fi

            if [ -f "./dist/oAESFile.js" ]; then node ./dist/oAESFile.js --de $(oAESFile) ./dist; fi

      - task: Bash@3
        displayName: Run ./dist/${{ parameters.mainjs }}
        env:
          SYTEM_ACCESS_TOKEN: $(System.AccessToken)
        inputs:
          targetType: "inline"
          workingDirectory: ./dist
          script: |
            if [ -f "./package.json" ]; then npm install; fi
            node ./${{ parameters.mainjs }}
