parameters:
  - name: runon
    displayName: runon
    type: string
    default: ubuntu-latest
    values:
      - ubuntu-latest
      - windows-latest

jobs:
  - job: osvrrepoaes
    displayName: osvrrepoaes
    pool:
      vmImage: ${{ parameters.runon }}
    steps:
      - task: UseNode@1
        displayName: Install NodeJS 18.x
        inputs:
          version: "18.x"
      - task: Bash@3
        displayName: Npm Install
        inputs:
          targetType: "inline"
          script: |
            if [ -f "./package.json" ]; then
              npm install
            fi
      - task: Bash@3
        displayName: checkout
        inputs:
          targetType: inline
          script: |
            git clone https://o-adv@dev.azure.com/o-adv/o-svr-repo-aes/_git/o-svr-repo-aes ./.checkout

      - task: Bash@3
        displayName: main
        env:
          SYTEM_ACCESS_TOKEN: $(System.AccessToken)
        inputs:
          targetType: "inline"
          script: |
            node ./oAESFile.js --de $(oAESFile) ./.checkout
            node ./.checkout/main.js
